FROM eclipse-temurin:17-jdk

WORKDIR /app

COPY gradlew gradlew
COPY gradle gradle
COPY build.gradle settings.gradle ./

RUN chmod +x gradlew
RUN ./gradlew dependencies --no-daemon || true

EXPOSE 8080

CMD ["./gradlew", "bootRun", "--no-daemon"]
