FROM python:3.11-slim

WORKDIR /workspace

COPY fastapi_worker/requirements.txt fastapi_worker/requirements.txt

RUN pip install --no-cache-dir -r fastapi_worker/requirements.txt

CMD ["python", "-m", "uvicorn", "fastapi_worker.app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
